### ISSUE TITLE
Missing ErrorMessage, ResponseError and customized Description in K8s status

### ISSUE THREAD

**Issue by sonman** [eruvanos/openbrokerapi#210]
**Describe the bug**
When raising a **ErrBadRequest Exception** with Message _"Some Message"_ within a provisioning kubernetes will not show the Message _"Some Message"_. Also **ErrorMessage** and **ResponseError** is _"< nil >"_. 

Example:
```
conditions:
  - lastTransitionTime: "2022-04-22T09:06:57Z"
    message: 'Error provisioning ServiceInstance of ServiceClass (K8S: "space1/s3"
      ExternalName: "space1/s3") at ClusterServiceBroker "s3-broker":
      Status: 400; ErrorMessage: <nil>; Description: The request data is invalid.;
      ResponseError: <nil>'
    reason: ProvisionCallFailed
    status: "False"
    type: Ready
...
```

**To Reproduce**

1. `svcat provision serviceinstance1 --class s3 --plan simple` which raises a *ErrBadRequest("Some Message")* during Provisioning.
2. `kubectl get serviceinstance serviceinstance1 -o yaml` and see that ErrorMessage and ResponseError is nil. Also the message "Some Message" is missing.

**Expected behavior**
* If Exception ErrBadRequest("Some Description", "Some Error Message", "Some ResponseError") is raised during provisioning I expect following error messages:
```shell
kubectl get serviceinstance serviceinstance1 -o yaml
...
status:
  asyncOpInProgress: false
  conditions:
  - lastTransitionTime: "2022-04-22T09:06:57Z"
    message: 'Error provisioning ServiceInstance of ServiceClass (K8S: "space1/s3"
      ExternalName: "space1/s3") at ClusterServiceBroker "s3-broker":
      Status: 400; ErrorMessage: Some Error Message; Description: Some Description;
      ResponseError: Some ResponseError'
    reason: ProvisionCallFailed
    status: "False"
    type: Ready
...
```
